name: example of action using Github OIDC 

on: 
  workflow_dispatch:
  push:

jobs:
  Read:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for configure AWS credentials.
      contents: read # Required for checkout the source code.

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::385942912907:role/chautest_github_access
        # role-to-assume: arn:aws:iam::123456789012:role/iam_role_name # Craft your own IAM role.
        aws-region: 'ap-southeast-2'
          
    - name: verify identity
      run: aws sts get-caller-identity # or some AWS action.
