name: Test AWS Federation in Github Actions
on: 
  push:
    paths-ignore:
    - 'README.md'

jobs:
  Read:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::385942912907:role/chautest_github_access
        aws-region: 'ap-southeast-2'
          
    - name: verify identity
      run: aws sts get-caller-identity # or some AWS action