name: Test AWS Federation in Github Actions
on: 
  push:
    paths-ignore:
    - 'README.md'

env:
  AWS_ROLE_ARN: arn:aws:iam::538713613814:role/Github_Federated_Access_Role
  AWS_DEFAULT_REGION: 'ap-southeast-2'

jobs:
  Read:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
    
    - name: Upload to S3 --dryrun
      run: |
        aws s3 sync \
        --acl public-read --follow-symlinks --delete --dryrun --sse AES256 \
        . \
        s3://sm-probono-frontend-bucket/who/qa-en
    
    - name: verify
      run: ls -lrt $GITHUB_WORKSPACE

    # - name: Upload to S3 - index.html with different caching --dryrun
    #   run: |
    #     aws s3 sync \
    #     --acl public-read --follow-symlinks --cache-control "no-cache" --dryrun --sse AES256 \
    #     $GITHUB_WORKSPACE/index.html \
    #     s3://sm-probono-frontend-bucket/who/qa-en
    
    - name: Invalidate Cloudfront
      run: |
        aws cloudfront create-invalidation \
        --distribution-id=E18DN7GJQWEP2J \
        --paths '/*'
          
    # - name: verify identity
    #   run: aws sts get-caller-identity # or some AWS action