name: Test via reading S3 content
on: 
  push:
    paths-ignore:
    - 'README.md'

env:
  AWS_ROLE_ARN: arn:aws:iam::385942912907:role/chautest_github_access
  AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
  AWS_DEFAULT_OUTPUT: 'json'
  AWS_DEFAULT_REGION: 'ap-southeast-2'

jobs:
  Read:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo AWS_WEB_IDENTITY_TOKEN_FILE=${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }} >> $GITHUB_ENV
        echo AWS_ROLE_ARN=${{ env.AWS_ROLE_ARN }} >> $GITHUB_ENV
        echo AWS_DEFAULT_REGION=${{ env.AWS_DEFAULT_REGION }} >> $GITHUB_ENV
        curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
    
    - name: verify identity
      run: aws s3 ls

